#!/usr/bin/env bash
set -euo pipefail

bundle install
bundle exec jekyll build
python -m pip install -r requirements.txt --quiet
mkdir -p junit-reports
python -m pytest tests/ --junit-xml=junit-reports/results.xml
