#!/usr/bin/env bash
set -euo pipefail

bundle install
bundle exec jekyll build
pip install -r requirements.txt --quiet
mkdir -p junit-reports
python -m pytest tests/ --html=junit-reports/report.html --self-contained-html
