name: build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - uses: actions/setup-python@v4
      - run: gem install bundler jekyll
      - run: ./build_and_test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          detailed_summary: true
          report_paths: junit-reports/results.xml
