name: Jekyll site CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to ftp server
      env:
        FTP_USER: '${{ secrets.FTP_USER }}'
        FTP_PASSWORD: '${{ secrets.FTP_PASSWORD }}'
        FTP_SERVER: '${{ secrets.FTP_SERVER }}'
      run: ./deploy.py
        
      
